spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employee_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update #for development, use none or validate for production





